{% set version = '1.5-5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mnormt
  version: {{ version|replace("-", "_") }}

source:
  fn: mnormt_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/mnormt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mnormt/mnormt_{{ version }}.tar.gz
  sha256: ff78d5f935278935f1814a69e5a913d93d6dd2ac1b5681ba86b30c6773ef64ac

build:
  merge_build_host: True  # [win]
  number: 1002
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_fortran') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('mnormt')"           # [not win]
    - "\"%R%\" -e \"library('mnormt')\""  # [win]

about:
  home: http://azzalini.stat.unipd.it/SW/Pkg-mnormt
  license: GPL-2 | GPL-3
  summary: Functions are provided for computing the density and the distribution function of
    multivariate normal and "t" random variables, and for generating random vectors
    sampled from these distributions.   Probabilities are computed via non-Monte Carlo
    methods; different routines  are used in the case d=1, d=2, d>2, if d denotes the
    number of dimensions.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
