{% set version = "1.5-7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mnormt
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mnormt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mnormt/mnormt_{{ version }}.tar.gz
  sha256: cf3d77d09fe904f27181778e6eb9cde9c9c1a9ec3c89e63617ea7301e0a61bf8

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('mnormt')"           # [not win]
    - "\"%R%\" -e \"library('mnormt')\""  # [win]

about:
  home: http://azzalini.stat.unipd.it/SW/Pkg-mnormt
  license: GPL-2 | GPL-3
  summary: Functions are provided for computing the density and the distribution function of multivariate normal and "t" random variables, and for generating random vectors sampled from these distributions. Probabilities are computed via non-Monte Carlo methods; different routines are used in the case d=1, d=2, d>2, if d
    denotes the number of dimensions.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: mnormt
# Version: 1.5-6
# Date: 2020-02-02
# Title: The Multivariate Normal and t Distributions
# Author: Fortran code by Alan Genz and other people referred to in the code, R code by Adelchi Azzalini
# Maintainer: Adelchi Azzalini <adelchi.azzalini@unipd.it>
# Depends: R (>= 2.2.0)
# Description: Functions are provided for computing the density and the distribution function of multivariate normal and "t" random variables, and for generating random vectors sampled from these distributions. Probabilities are computed via non-Monte Carlo methods; different routines are used in the case d=1, d=2, d>2, if d denotes the number of dimensions.
# License: GPL-2 | GPL-3
# URL: http://azzalini.stat.unipd.it/SW/Pkg-mnormt
# NeedsCompilation: yes
# Packaged: 2020-02-02 17:21:41 UTC; aa
# Repository: CRAN
# Date/Publication: 2020-02-03 10:00:02 UTC
