appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: ItMdh2/bzWnT4+0JJByNGua3g+IIRka8+hG5gTtQI7KqjW/hgRSYZE6UoBhQDJMtjCVczMPdR+7PtAn/u6KvktG9T11EKIoqzWpytAe0z4uu/igr4aV2gP6WmA2AuQTQwlPhpeFPB9552SNMmC92Ot6Q4eLbR3yulcBf3hVaosl1zDEKd4eV4kMjZmsqSkTtOnYQdPxCXcmKNGD3jmJSeoSGRfqsJWAgD4G40JBbegCMrDBpSu/lswKrVy8amTTZRC/PnJghzWDQ2GuBm+GNur6WIHZ20umqza1FsyQISfW/xJnp7gm3Ri7T8JB08JiOafh1QjHG9R6CprMDCn6YEd2UnMA4hXgXVUw48Rm78xpXkFNVuSo6Zd2AoyuHn7gkjtxMcXaz/hrP+HKVNbQ91dmb03Rfx/OjdDUATi0y0B0Ut0MEWKhYIDE6/tkro7W6fEkFAqZAuq9yRcLkC9WVybSOjTfBEwV2rtqaQ6EM4jOIREN63nrqTQyvAL66JBQGHEBthb5UG7ozyAM9tj3juJTnFUtIdB8UZ7p8cJTefRagIChqOGiFOdirLdT7I1ffF64B/Z5TVGUVzAHGsa1jeIRhJ4I9Jit4Q0/ni63CpHGvrTo5uF+jInFRmldi/Y2o0bwcbFstAB2RBg6Osz5bk/3E+BlKOqtecPB9YBIVneM=}
bot:
  automerge: true
